---
collections:
- name: ansible.netcommon
  version: 2.4.0
  source: https://galaxy.ansible.com
  type: galaxy
- name: community.general
  version: 3.8.0
  source: https://galaxy.ansible.com
  type: galaxy
- name: community.vmware
  version: 1.15.0
  source: https://galaxy.ansible.com
  type: galaxy
