---
collections:
- name: ansible.netcommon
  version: 2.5.0
  source: https://galaxy.ansible.com
  type: galaxy
- name: community.general
  version: 4.1.0
  source: https://galaxy.ansible.com
  type: galaxy
