---
- name: Update APT Repositories
  apt:
    update_cache: yes
  become: true

- name: Install APT Packages
  vars:
    apt_packages:
      - sshpass
  loop: "{{ apt_packages }}"
  apt:
    name: "{{ item }}"
    state: latest
  become: true

- name: Install Python Modules
  vars:
    python_modules:
      - jmespath
      - openpyxl
  loop: "{{ python_modules }}"
  pip:
    name: jmespath
    state: latest
  become: true
